name: CI/CD for Hello World C++

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up build environment
      - name: Install build tools and CMake
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      # Step 3: Build the project
      - name: Build the project
        run: |
          cd build
          cmake --build .

      # Step 4: Run the executable
      - name: Run the program
        run: ./build/EDA_PROJECT
   
